We will evaluate our regression models on a given dataset and will find out which is best

Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Import the dataset

In [5]:
data=pd.read_csv('./datasets/Ultimate_Data.csv')
data.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

Splitting into dependent and independent variables

In [6]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
x

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [7]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

Splitting the data into x train and y train

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

Training the Multiple Linear Regression Model

In [9]:
from sklearn.linear_model import LinearRegression
linear_regressor=LinearRegression()
linear_regressor.fit(x_train,y_train)

LinearRegression()

Predicting test results

In [13]:
y_pred = linear_regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))   #ek saath dekh sake

[[455.68 455.27]
 [438.73 436.31]
 [434.16 440.68]
 ...
 [482.17 479.53]
 [435.42 435.76]
 [458.76 457.1 ]]


Let's evaluate the model based on r2 score

In [16]:
from sklearn.metrics import r2_score
print(f"The r2 score of the model is {r2_score(y_test,y_pred)*100}")
#93.01 percentage

The r2 score of the model is 93.01046431962187


Polynomial Regression

In [17]:
from sklearn.preprocessing import PolynomialFeatures
pf=PolynomialFeatures(degree=4)  #polynomial regressor of degree 4
x_poly=pf.fit_transform(x_train)  #converting into required matrix
print(x_poly) 

[[1.00e+00 2.19e+01 4.90e+01 ... 7.99e+09 7.01e+08 6.15e+07]
 [1.00e+00 1.11e+01 4.04e+01 ... 5.91e+09 4.32e+08 3.16e+07]
 [1.00e+00 8.49e+00 3.96e+01 ... 8.03e+09 6.90e+08 5.93e+07]
 ...
 [1.00e+00 2.78e+01 6.92e+01 ... 2.14e+09 9.67e+07 4.37e+06]
 [1.00e+00 1.23e+01 4.15e+01 ... 8.23e+09 7.25e+08 6.39e+07]
 [1.00e+00 1.18e+01 4.05e+01 ... 9.89e+09 9.49e+08 9.11e+07]]


Train the model

In [18]:
polynomial_regressor=LinearRegression()
polynomial_regressor.fit(x_poly,y_train)

LinearRegression()

Prediction of the test results 
firstly convert the x_test into required matrix of poly_x

In [19]:
y_pred=polynomial_regressor.predict(pf.transform(x_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[455.91 455.27]
 [437.66 436.31]
 [434.51 440.68]
 ...
 [482.63 479.53]
 [435.28 435.76]
 [460.01 457.1 ]]


Let's evaluate this model

In [21]:
print(f"The r2 score of this model is {r2_score(y_test,y_pred)*100}")
#94.31 percentage better than multiple linear regression

The r2 score of this model is 94.3189914172793


Support Vector Regression

In support vector we have to convert the y into 2d before the splitting into train and test or we can do it later also

In [22]:
y_train=y_train.reshape(len(y_train),1)
y_test=y_test.reshape(len(y_test),1)

Feature Scaling is needed in support vector

In [23]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
sc_y=StandardScaler()
y_train=sc_y.fit_transform(y_train)

Train the model

In [24]:
from sklearn.svm import SVR
support_vector_regressor=SVR(kernel='rbf')
support_vector_regressor.fit(x_train,y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

Prediction of test set results

In [28]:
y_pred=sc_y.inverse_transform(support_vector_regressor.predict(sc_x.transform(x_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

#hamne y_pred ko inverse transfor kr k liya hai and  y_test ko kabhi transform hi nhi kiya

[[456.77 455.27]
 [437.11 436.31]
 [434.62 440.68]
 ...
 [483.16 479.53]
 [435.35 435.76]
 [458.55 457.1 ]]


Evaluate the model

In [30]:
print(f"The r2 score of support vector regression is {r2_score(y_test,y_pred)*100}")
#94.68 percent

The r2 score of support vector regression is 94.68461924240114


Decision Tree Regression

we have to again split into x_train due to use of scaler in previous model

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

Training the model

In [35]:
from sklearn.tree import DecisionTreeRegressor
decision_regressor=DecisionTreeRegressor(random_state=42)
decision_regressor.fit(x_train,y_train)

DecisionTreeRegressor(random_state=42)

Prediction of test results

In [43]:
y_pred=decision_regressor.predict(x_test)
np.printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[455.57 455.27]
 [436.96 436.31]
 [431.73 440.68]
 ...
 [483.3  479.53]
 [429.28 435.76]
 [456.35 457.1 ]]


Evaluation of model

In [45]:
print(f"The r2 score of the model is {r2_score(y_test,y_pred)*100}")
#93.27 percent

The r2 score of the model is 93.27935649059674


Random Forest Regression

In [52]:
from sklearn.ensemble import RandomForestRegressor
random_forest_regressor=RandomForestRegressor(n_estimators=100,random_state=42)
random_forest_regressor.fit(x_train,y_train)

RandomForestRegressor(random_state=42)

Prediction of Test Set

In [53]:
y_pred=random_forest_regressor.predict(x_test)
np.printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[455.75 455.27]
 [435.98 436.31]
 [434.75 440.68]
 ...
 [484.08 479.53]
 [434.12 435.76]
 [456.58 457.1 ]]


Evaluation of model

In [54]:
print(f"The r2 score of the random forest is {r2_score(y_test,y_pred)*100}")
#95 percent

The r2 score of the random forest is 96.36693399560956


so for this dataset random forest is best